# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'apertureNameDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(734, 425)
        Dialog.setMinimumSize(QtCore.QSize(600, 0))
        Dialog.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.apertureNameEdit = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.apertureNameEdit.setFont(font)
        self.apertureNameEdit.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.apertureNameEdit.setMaxLength(80)
        self.apertureNameEdit.setObjectName("apertureNameEdit")
        self.verticalLayout.addWidget(self.apertureNameEdit)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Vertical)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 0, 1, 1, 1)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Enter desired aperture name"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p>Enter name for aperture...</p><p>Apertures that are given a name containing \'track\' will automatically be placed as yellow tracking<br/>apertures. The default circular mask size will be taken from the entry in the <span style=\" font-weight:700; color:#0000ff;\">Pref.</span> tab.</p><p>If you want to base NRE on this star, begin the name with \'psf-star\' (without the quotes) or click<br/>on the <span style=\" font-weight:700; color:#0000ff;\">add NRE aperture</span> menu item.<br/><br/>A star/aperture so named will be the one used in estimating the instrumental psf when the<br/>generate NRE psf\' button is pressed.</p><p><br/>Of course, only a single aperture with a name starting with \'psf-star\' is allowed, but if you want other stars<br/>to use NRE, put the string \'psf-star\' somewhere in the name. (Usually the psf would be <br/>determined from the target star, but you can control this by appropriate naming.)</p><p><br/>If you want to suppress the re-centering of static masks within an aperture, put the string <br/>\'no-rc\' (or \'no_rc\' or \'no rc\') somewhere in the name. (Dynamic masks must relocate to do their job, <br/>so the presence of a \'no-rc\' will be ignored.)</p><p><br/>Apertures named \'empty\' or \'no-star\', or \'no_star\' or \'no star\' are treated as though they contain <br/>the \'no-rc\' string - this is because the N-brightest-pixel-mass-centroid re-centering of static circular masks,<br/>if allowed to \'hunt\' within the aperture, will find opportunistic clumps of pixels that are a little brighter <br/>than other clumps and thus generate a tiny, but false, signal - disabling recentering prevents this.</p></body></html>"))
